### ISSUE TITLE
With the TDM update, the plug-in for BepInEX5 no longer works.

### ISSUE THREAD

**Issue by re-unknown** [Fluto/TaikoMods#10]
As the title says, BepInEX5 no longer works because the TDM build has been changed from Mono to IL2CPP.
However, BepInEX6 works with IL2CPP, but the plugin needs to be updated for BepInEX6.

**Comment by Fluto** [comment]
That's correct. I'll look into it when I have free time. As some core code has changed in the new version of the game that I need to account for

**Comment by tamamoto** [comment]
Hello! Please add a wallet for donation!

**Comment by gnargle** [comment]
I would also appreciate an update on this mod when possible :)

**Comment by juccatan** [comment]
I hope to see an update on this soon! Switching between the latest version for online play and version 1.2 for custom songs isn't necessarily the most optimal way of playing 😓

**Comment by Fluto** [comment]
It is pretty annoying. 
I've been AWOL for a bit doing other stuff sadly. 

Unfortunately the architecture of the newer updates is completely different. Before it was as simple as writing code, and injecting it into the game. Now I need to decode what their new functionality is doing using various decompilation techniques 😅. 

It'll be some time before I make an update, but I still intend to, one day :p

**Comment by Meta-KnightX** [comment]
Any update on the plugin development? It's been a few months and I've recently gotten interest in this plugin.

**Comment by Fluto** [comment]
Not yet, you can still use the mod with an older version of the game for now. 
Making the mod for the newest update will require a bit of a re-write and I don't have the time for it at the moment :(

**Comment by Meta-KnightX** [comment]
Thanks for letting me know. How can I go about downgrading the game?

**Comment by Fluto** [comment]
You should be able to find a guide on the Taiko Modding server over here.
https://discord.gg/HFm37aA5zr

**Comment by Fluto** [comment]
It is done 
![52e](https://user-images.githubusercontent.com/7686594/184521820-e299303e-0145-4f0d-95ea-2cc1beadfb96.png)
