### ISSUE TITLE
Incorrect Score Appearing in Results Screen

### ISSUE THREAD

**Issue by Meta-KnightX** [Fluto/TaikoMods#13]
During gameplay; the score, percent scale, and combo adds up correctly.

However, when completing a song, the game thinks it's a fail.
![184564974-7db76ef9-53ea-453c-a17c-21232db5b4d4](https://user-images.githubusercontent.com/36248204/184566164-be12c43c-09e0-443d-99c2-b58525f467ae.png)

The score that is saved to the particular song is presented correctly, and should still update the high score of each song as intended.
This issue occurs in both official and custom songs.

Additional loaded plugin: TaikoModStuff

**Comment by Fluto** [comment]
Thanks! Should hopefully be fixed now :)
