### ISSUE TITLE
Different Folder Name / Leaderboard Question

### ISSUE THREAD

**Issue by Deathmaw** [Fluto/TaikoMods#2]
Is it possible to have a different folder name? I was trying with say folder name as "Song Name Blah Blah Blah" but the error log showed it tried to find the sound file in a folder that matched the id in the data.json

While I'm here, I do have a question more so than an issue, I know this saves the scores to its own file but does this bypass any calls to the leaderboards on the Xbox side? say DLC launches and I'm using a id that matches, would it attempt to post my score? or if for some reason I already used one in the base game, would it try submit the score? if so hopefully this can be patched out, wasn't sure if the game just always tries to submit a score at a certain point and if it was disabled here.

**Comment by Fluto** [comment]
In an upcoming update I'll have multi folder support :)

In the case of leaderboards; Leaderboards are hand made per song by the developers. Meaning they wont have leaderboards for custom songs. Additionally at the moment, IDs in the range that they use (0 - 400) are currently not accepted by my mod to avoid this issue. In fact it will reassign a new ID for any custom songs in that range for you automatically

**Comment by Deathmaw** [comment]
Cool!

If they made a a leaderboard though I assume it goes based on the id? so like "weare0" would a custom song try to post to that leaderboard if it found it?

**Comment by ghost** [comment]
right now install everything perfect like 1 week ago but in this update it does not save the crowns of the personalized songs
