### ISSUE TITLE
crowns are not saved

### ISSUE THREAD

**Issue by ghost** [Fluto/TaikoMods#6]
right now install everything perfect like 1 week ago but in this update it does not save the crowns of the personalized songs

remove and install everything like 5 times but still the same when closing the game and entering nothing is saved

**Comment by Fluto** [comment]
The current release of the mod isn't loading saves, it still should be saving however. I've already made a fix but have not built it just yet as there is further work to be done.

**Comment by ghost** [comment]
thank you very much for the answer I was like crazy deleting and installing everything again!

Thank you very much for your beautiful work!

**Comment by Fluto** [comment]
Fixed in the [v2.1.0 release](https://github.com/Fluto/TakoTako/releases/tag/v2.1.0)
