### ISSUE TITLE
Custom songs not saving high score

### ISSUE THREAD

**Issue by guyman70718** [Fluto/TaikoMods#8]
Some of my custom songs (all tja) are saving the high score between game restarts but most aren’t. Out of 5 songs I installed, only 1 saved crowns/score through restart.

**Comment by guyman70718** [comment]
Just want to add that the song that was storing the high score before just lost its high score, so all my custom song high scores are cleared on game restart

**Comment by Fluto** [comment]
#6 Duplicate issue

**Comment by Fluto** [comment]
Fixed in the [v2.1.0 release](https://github.com/Fluto/TakoTako/releases/tag/v2.1.0)
